Ti.include(
    'listDomains.js'
);

windowFunctions['SimpleDb'] = function (evt) {
    var win = createWindow();
    var offset = addBackButton(win);
    var table = Ti.UI.createTableView({
        backgroundColor: '#fff',
        top: offset + u,
        data: createRows([
            'ListDomains',
            'ListDomainWithInvalidParams',
            'ListDomainWithValidParams',
            'CreateDomain',
            'CreateEmptyDomain',
            'CreateInValidDomain',
            'DeleteDomain',
            'DeleteEmptyDomain',
            'DeleteInvalidDomain',
            'BatchDeleteAttributesEmptyItemName',
            'BatchDeleteAttributesInvalidItemName',
            'BatchDeleteAttributesEmptyAttributes',
            'BatchDeleteAttributesInvalidAttributesName',
            'BatchDeleteAttributesInvalidAttributesValue',
            'BatchDeleteAttributesEmptyDomainName',
            'BatchDeleteAttributesInvalidDomain',
            'ValidBatchDeleteAttributes',
            'BatchPutAttributesEmptyItemName',
            'BatchPutAttributesEmptyAttributesValue',
            'BatchPutAttributesEmptyAttributesName',
            'BatchPutAttributesEmptyDomainName',
            'BatchPutAttributesInvalidDomainName',
            'BatchPutAttributesInvalidAttributesName',
            'BatchPutAttributesInvalidAttributesValue',
            'BatchPutAttributesInvalidItemName ',
            'BatchPutAttributesInvalidReplaceValue',
            'validBatchPutAttributes',
            'deleteAttributesEmptyDomainName',
            'deleteAttributesInvalidDomainName',
            'deleteAttributesEmptyItemName',
            'deleteAttributesInvalidItemName',
            'deleteAttributesInvalidAttributeName',
            'deleteAttributesInvalidAttributeValue',
            'deleteAttributesInvalidExpectedExistsValue',
            'deleteAttributesInvalidExpectedName',
            'deleteAttributesInvalidExpectedValue',
            'ValidDeleteAttributes',
            'DomainMetadataInvalidDomainName',
            'DomainMetadataEmptyDomainName',
            'validDomainMetadata',
            'GetAttributesEmptyDomainName',
            'GetAttributesInvalidDomainName',
            'GetAttributesEmptyItemName',
            'GetAttributesInvalidItemName',
            'GetAttributesInvalidAttributeName',
            'GetAttributesInvalidConsistentRead',
            'ValidGetAttributes',
            'PutAttributesEmptyDomainName',
            'PutAttributesInvalidDomainName',
            'PutAttributesEmptyItemName',
            'PutAttributesInvalidItemName',
            'PutAttributesEmptyAttributeName',
            'PutAttributesInvalidAttributeName',
            'PutAttributesEmptyAttributeValue',
            'PutAttributesInvalidAttributeValue',
            'putAttributesInvalidExpectedExistsValue',
            'putAttributesInvalidExpectedName',
            'putAttributesInvalidExpectedValue',
            'ValidPutAttributes',
            'SelectEmptySelectExpression',
            'SelectInvalidSelectExpression',
            'SelectInvalidSelectExpression',
            'SelectInvalidNextToken',
            'SelectInvalidConsistentRead',
            'ValidSelect',
        ])
    });
    table.addEventListener('click', handleOpenWindow);
    win.add(table);
    win.open();
};